apiVersion: v1
kind: Secret
metadata:
 annotations:
   serving.kserve.io/s3-endpoint: http://seaweedfs.seaweedfs.svc:8333 
   serving.kserve.io/s3-usehttps: "0" 
   serving.kserve.io/s3-region: "us-east-1"
   serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
 name: storage-config
stringData:
 "AWS_ACCESS_KEY_ID": "admin"
 "AWS_SECRET_ACCESS_KEY": "admin"
