apiVersion: v1
kind: Pod
metadata:  
  labels:
    app: seaweedfs
  name: seaweedfs
  namespace: seaweedfs
spec:
  containers:
  - args:
    - mini
    - -ip=0.0.0.0
    - -dir=/data1
    - -s3
    env:
    - name: AWS_ACCESS_KEY_ID
      value: admin
    - name: AWS_SECRET_ACCESS_KEY
      value: admin
    image: quay.io/jooholee/model-seaweedfs:latest
    imagePullPolicy: Always
    name: seaweedfs
    ports:
    - containerPort: 8333
      name: s3
      protocol: TCP
    - containerPort: 23646
      name: admin-ui
      protocol: TCP
    - containerPort: 9333
      name: master-ui
      protocol: TCP
    - containerPort: 8888
      name: filer-ui
      protocol: TCP
    - containerPort: 9340
      name: volume
      protocol: TCP
